### PR TITLE
karin: Update overlay from 32.2.A.0.224

### PR DESCRIPTION
**Pull request by humberos**
Signed-off-by: Humberto Borba humberos@gmail.com
Change-Id: I9a194cd61ab9597ef8b69fe407be965a1a26a056

### CODE REVIEW

**Comment by jerpelea** [comment]
please split this into multiple patches

**Comment by humberos** [comment]
Yes, I will.
Please let me know if there is something that should be a common entry for kitakami or common repos 

Ping @erikcas @alviteri @oshmoun

**Comment by humberos** [comment]
I've just tested them on karin (aosp build).
No problems here.
I also used these changes: 
https://github.com/sonyxperiadev/device-sony-karin/pull/28

**Comment by oshmoun** [comment]
umm, maybe an ignorant question, but where would I see those values in stock rom? so I can compare

**Comment by erikcas** [comment]
not able to test atm. Sumire is killed atm

**Comment by humberos** [comment]
@oshmoun you must be able to decompile APK (apktool) then just check if AOSP supports the overlay.

**Comment by humberos** [comment]
any progress here ? I mean about if there are common items.

**Comment by oshmoun** [comment]
woops, sorry about that!
here's what's found so far:

power_profile.xml:
all new values are the same except radio.active, which has value 118.02
https://github.com/sonyxperiadev/device-sony-karin_windy/pull/18/commits/bff3edff7b7f1dea8786dc35c3764281849a8fc3#diff-5aa91e94b1555af5344bf3c4d343b922R16

same values:
config_screenBrightnessDoze
config_screenBrightnessDark
config_suspendWhenScreenOffDueToProximity
config_bluetooth_le_peripheral_mode_supported
config_powerDecoupleInteractiveModeFromDisplay
config_dozeAfterScreenOff
config_device_vt_available
config_maximumScreenDimDuration

doesn't exist on stock:
doze_display_state_supported: doesn't exist on stock

different values:
config_bluetooth_operating_voltage_mv: value on stock is 3700
config_wifi_operating_voltage_mv: value on stock is 3700
config_bluetooth_rx_cur_ma: value on stock is 31
config_bluetooth_tx_cur_ma: value on stock is 31
config_wifi_idle_receive_cur_ma: value on stock is 1
config_wifi_active_rx_cur_ma: value on stock is 63
config_wifi_tx_cur_ma: value on stock is 331

**Comment by humberos** [comment]
Oh! Thank you @oshmoun!
IMHO I think it will be better to merge these changes for now then just do a "commonizing" step after when all overlays are updated (from others kitakamies).
Again, thank you!

**Pull request closed without merging**
